services:
  mysql:
    image: mysql:8.0
    container_name: warehouse-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./sql/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql:ro
      - ./sql/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql:ro
volumes:
  mysql_data: